---
# tasks file for start_svc
- name: "Starting Service"
  service:
    name: "{{ service_name }}"
    state: started

#net start fwd - run start-service.bat
#net start windows_service - service_name = fwd
- name: start the service
  script: start-service.bat
   tags: 
        - tomcat_apps