--- 
- 
  become: true
  gather_facts: true
  hosts: "65.2.10.212"
  name: "play to deplou a java app"
  tasks: 
    - 
      name: "install {{ java_version }}"
      yum: 
        name: "{{ java_version }}"
        state: present
    - 
      name: "create directory"
      command: "mkdir /opt/apps"
    - 
      get_url: 
        dest: "/opt/apps/{{ app_server }}"
        url: "https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.62/bin/{{ app_server }}"
      name: "download tomcat"
    - 
      name: "extract archive"
      unarchive: 
        dest: /opt/apps/
        src: "/opt/apps/{{ app_server }}"
    - 
      name: "Start Tomcat"
      service: 
        enabled: true
        name: tomcat
        state: started
  vars: 
    - 
      app_server: apache-tomcat-9.0.62
    - 
      java_version: java-1.8.0-openjdk

