---
- name: Restart Apache2.4 service
  ansible.windows.win_service:
    name: Apache2.4
    state: restarted

- name: Apache2.4.23-Redhat
  ansible.windows.win_service:
    name: Apache2.4.23-Redhat
    state: restarted
    when: 
     - server == "proda" 
     - server == "prodb"