---
- name: "Deploy D2C Nuxt App"
  hosts: "win"
  gather_facts: yes
  vars:
    myurl: "https://releases.ansible.com/ansible/ansible-2.9.25.tar.gz"
    mydest: 'C:\Users\Administrator\Desktop\ansible-2.9.25.tar.gz'
  tasks:
   - name: "Stop Application before deployment"
     include_role:
       name: "stop_svc"
   - name: download file
     ansible.windows.win_get_url:
        url: "{{ myurl }}"
        dest: "{{ mydest }}"
   - name: "Deploy Artifacts"
     include_role:
       name: "deploy_svc"
     tags: 
       - jboss_app
   - name: "Start SVC"
     include_role:
       name: "start_svc"
   